# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

fibonacciSequence = Enumerator.new do |current_num|
  current_num.yield first_num = 1
  current_num.yield second_num = 2
  while true
    next_num = first_num + second_num
    current_num.yield next_num
    first_num = second_num
    second_num = next_num
  end
end

sum = 0
while (number = fibonacciSequence.next()) < 4_000_000 do
  sum += number if (number % 2) == 0
end

puts sum